version: 2
jobs:
  build:
    docker:
      - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build application Docker image
          command:
            docker build -t gcr.io/${GCLOUD_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
      - run:
          name: tag and push application Docker image
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > keyfile.json
            docker login -u _json_key -p "$(cat keyfile.json)" gcr.io
            docker tag gcr.io/${GCLOUD_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} gcr.io/${GCLOUD_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:latest
            docker push gcr.io/${GCLOUD_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}
  container_publish_tag:
    working_directory: ~/auth_glue_svc
    docker:
      - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build application Docker image
          command:
            docker build -t gcr.io/${GCLOUD_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
      - run:
          name: Log in and push
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > keyfile.json
            docker login -u _json_key -p "$(cat keyfile.json)" gcr.io
            docker pull gcr.io/${GCLOUD_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} &
            docker tag gcr.io/${GCLOUD_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} gcr.io/${GCLOUD_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG} &
            docker push gcr.io/${GCLOUD_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              ignore: /^v.*/
      - publish_tag:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
